examples:
  disable:
    - if: IDF_VERSION_MAJOR < 5 and CONFIG_NAME in ["esp32_c3_lcdkit", "esp32_s3_lcd_ev_board", "esp32_s3_usb_otg", "m5stack_core_s3"]
      reason: Example depends on BSP, which is supported only for IDF >= 5.0
    - if: IDF_VERSION_MAJOR < 5 and IDF_TARGET in ["esp32c2", "esp32p4", "esp32c5", "esp32c6"]
      reason: Example depends on target, which is supported only for IDF >= 5.0

components/esp_lvgl_port/examples/i2c_oled:
  disable:
    - if: SOC_I2C_SUPPORTED != 1

components/lcd/esp_lcd_ssd1681/examples/epaper_lvgl_demo:
  disable:
    - if: SOC_GPSPI_SUPPORTED != 1

components/lcd/esp_lcd_ssd1681/examples/epaper_demo:
  disable:
    - if: SOC_GPSPI_SUPPORTED != 1

components/lcd/esp_lcd_gc9503/test_apps:
  disable:
    - if: IDF_VERSION_MAJOR < 5
      reason: Component is supported only for IDF >= 5.0

components/lcd/esp_lcd_ssd1681:
  disable:
    - if: IDF_VERSION_MAJOR < 5
      reason: Component is supported only for IDF >= 5.0
